using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/**
 * Class: Customer
 * Purpose: Used to store customer information.
 * Author: Team One to What
 * Properties:
 *   CustomerId: Unique ID generated by the DB for each instace of the customer class
     FirstName: Customer first name
     LastName: Customer last name
     DateCreated: Datetime generated to document when a customer instance was created
     LastInteraction: Datetime generated when a user visits the API, used to determine if they are still an active customer
     Active: boolean to identify is customer is still active
 */

namespace BangazonAPI.Models
{
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }
        [Required]
        public string FirstName {get; set;}
        [Required]
        public string LastName {get; set;}
        [Required]
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateCreated {get; set;}
        public DateTime lastInteraction {get; set;}
        [DefaultValue (false)]
        public bool Active {get; set;}
    }
}